name: Bug Report
description: File a bug/issue
title: '[BUG] <title>'
labels: ['bug', 'needs triage']
projects: ['infiniteobjects/5']
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report!

        👉 STEP 1: Write a concise but specific issue title in the box above.

        For example, if the problem is a render that keeps failing,
        your title might look like:

        > [bug] PrintId `12hss2` is not rendering correctly.
  - type: textarea
    id: bug_report_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: bug_report_area
    attributes:
      label: Affected product
      description: Where did you encounter the bug?
      placeholder: |
        Example: "Shopify Storefront"
    validations:
      required: true
  - type: textarea
    id: bug_report_reproduction
    attributes:
      label: Steps to Reproduce
      description: 'How do you trigger this bug? Please walk us through it step by step.'
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: bug_report_expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: bug_report_logs
    attributes:
      label: Log Output
      description: If applicable, add elevant log output
      render: shell
    validations:
      required: false
  - type: textarea
    id: bug_report_screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    id: bug_report_context
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
  - type: textarea
    id: bug_report_solution
    attributes:
      label: Possible Solution
      description: Have you thought about how we can fix this bug?
    validations:
      required: false
